name: Pre-commit Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install hadolint
        run: |
          curl -sSL -o /usr/local/bin/hadolint \
            https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  commit-messages:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Validate commit messages
        run: |
          git log --format="%H" --no-merges origin/${{ github.base_ref }}..HEAD \
          | while read -r sha; do
              git log -1 --format="%B" "$sha" > /tmp/commit-msg
              echo "Checking commit $sha: $(head -1 /tmp/commit-msg)"
              pre-commit run conventional-pre-commit \
                --hook-stage commit-msg \
                --commit-msg-filename /tmp/commit-msg
            done
